// This file contains a static list of Indian banks for IFSC Finder dropdown.
export const BANKS = [
  'State Bank of India',
  'HDFC Bank',
  'ICICI Bank',
  'Axis Bank',
  'Punjab National Bank',
  'Bank of Baroda',
  'Canara Bank',
  'Union Bank of India',
  'IndusInd Bank',
  'IDFC FIRST Bank',
  'Kotak Mahindra Bank',
  'Yes Bank',
  'Bank of India',
  'Central Bank of India',
  'Indian Bank',
  'UCO Bank',
  'Bank of Maharashtra',
  'IDBI Bank',
  'Federal Bank',
  'South Indian Bank',
  'RBL Bank',
  'Karur Vysya Bank',
  'Dhanlaxmi Bank',
  'City Union Bank',
  'Tamilnad Mercantile Bank',
  'Saraswat Bank',
  'Jammu and Kashmir Bank',
  'Karnataka Bank',
  'DCB Bank',
  'Andhra Bank',
  'Allahabad Bank',
  'Syndicate Bank',
  'Corporation Bank',
  'Oriental Bank of Commerce',
  'Vijaya Bank',
  'United Bank of India',
  'Indian Overseas Bank',
  'Punjab & Sind Bank',
  'Standard Chartered Bank',
  'HSBC',
  'Deutsche Bank',
  'Citi Bank',
  'DBS Bank',
  'Dena Bank',
  'Catholic Syrian Bank',
  'Lakshmi Vilas Bank',
  'Nainital Bank',
  'Bandhan Bank',
  'Equitas Small Finance Bank',
  'AU Small Finance Bank',
  'Ujjivan Small Finance Bank',
  'ESAF Small Finance Bank',
  'Fincare Small Finance Bank',
  'Jana Small Finance Bank',
  'North East Small Finance Bank',
  'Suryoday Small Finance Bank',
  'Utkarsh Small Finance Bank',
  'India Post Payments Bank',
  'Paytm Payments Bank',
  'Airtel Payments Bank',
  'Fino Payments Bank',
];
