import React from "react";
import { motion } from "framer-motion";
import { ArrowLeft, Target, Scale, CheckCircle, HelpCircle, TrendingUp, DollarSign, FileText, Briefcase } from "lucide-react";
import { Link } from "react-router-dom"; 

// --- CONFIGURATION START ---
const ARTICLE_TITLE = "The Ultimate 2026 Guide to CIBIL Score Mastery: Improve Your Creditworthiness for Loans";
const ARTICLE_SUBTITLE =
  "Unlock the secrets of your 3-digit financial fate. Learn how CIBIL score calculation works, discover advanced strategies to boost your score above 750, and ensure easy loan approvals from banks and NBFCs.";
const BACK_LINK = "/blogs/banking-guides"; 
const AUTHOR = "Advanced Financial Analytics Team";
const DATE = "Nov 18, 2025";
const READ_TIME = "45 min read"; // Increased read time due to expansion
// --- CONFIGURATION END ---

// Framer Motion variants
const pageVariants = {
  hidden: { opacity: 0, y: 50 },
  visible: {
    opacity: 1,
    y: 0,
    transition: {
      duration: 0.8,
      ease: "easeOut",
      staggerChildren: 0.05,
    },
  },
};

const itemVariants = {
  hidden: { opacity: 0, y: 30 },
  visible: {
    opacity: 1,
    y: 0,
    transition: {
      type: "spring",
      stiffness: 70,
      damping: 14,
    },
  },
};

// Reusable components
const SectionHeader: React.FC<{ title: string; icon: React.ElementType }> = ({ title, icon: Icon }) => (
  <motion.h2
    className="text-3xl sm:text-4xl font-extrabold text-gray-900 mt-12 mb-6 pt-4 border-t-2 border-blue-100 flex items-center"
    variants={itemVariants}
  >
    <Icon className="w-8 h-8 mr-3 text-blue-700" />
    {title}
  </motion.h2>
);

const SubHeader: React.FC<{ title: string }> = ({ title }) => (
  <motion.h3
    className="text-2xl font-bold text-gray-800 mt-8 mb-4 border-l-4 border-indigo-400 pl-3"
    variants={itemVariants}
  >
    {title}
  </motion.h3>
);

const BulletPoint: React.FC<{ text: string }> = ({ text }) => (
  <motion.li
    className="flex items-start mb-2 text-gray-700 leading-relaxed"
    variants={itemVariants}
  >
    <CheckCircle className="w-5 h-5 mr-3 mt-1 text-green-500 flex-shrink-0" />
    <span>{text}</span>
  </motion.li>
);

// --- MAIN COMPONENT ---
const UltimateCIBILGuidePage: React.FC = () => (
  <motion.div
    className="min-h-screen bg-gradient-to-br from-white/60 to-blue-50/80 py-12 px-4 md:px-12 font-inter"
    variants={pageVariants}
    initial="hidden"
    animate="visible"
  >
    <div className="max-w-5xl mx-auto">
      {/* Back Link */}
      <motion.div variants={itemVariants} className="mb-8">
        <Link
          to={BACK_LINK}
          className="inline-flex items-center text-blue-600 hover:text-blue-800 transition-colors font-semibold"
        >
          <ArrowLeft className="w-5 h-5 mr-2" />
          Back to Expert Banking Guides
        </Link>
      </motion.div>

      {/* Article Header (SEO H1) */}
      <motion.header variants={itemVariants} className="mb-10 pb-6 border-b border-blue-300">
        <h1 className="text-4xl sm:text-6xl font-extrabold text-gray-900 mb-4 drop-shadow-sm bg-clip-text text-transparent bg-gradient-to-r from-blue-600 to-indigo-700 leading-tight">
          {ARTICLE_TITLE}
        </h1>
        <p className="text-xl text-gray-700 leading-relaxed italic mt-4">
          {ARTICLE_SUBTITLE}
        </p>
        <div className="flex text-sm text-gray-500 mt-6 space-x-6">
          <span>By <strong>{AUTHOR}</strong></span>
          <span>•</span>
          <span>{DATE}</span>
          <span>•</span>
          <span>{READ_TIME}</span>
        </div>
      </motion.header>

      {/* Article Content */}
      <article className="text-gray-800 leading-relaxed space-y-8">

        <motion.p variants={itemVariants} className="text-xl font-semibold p-4 bg-blue-50 rounded-lg border-l-4 border-blue-600">
          In India's financial landscape, your <strong>CIBIL Score</strong> is more than just a number—it’s the definitive measure of your <strong>creditworthiness</strong>. Whether you are applying for a <strong>Home Loan</strong>, a low-interest <strong>Personal Loan</strong>, or a premium <strong>Credit Card</strong>, banks will always check your CIBIL report. Understanding the scoring system is the first step toward financial freedom and securing the best <strong>interest rates</strong> on the market.
        </motion.p>

        {/* SECTION 1: CIBIL Fundamentals */}
        <SectionHeader title="1. Decoding the CIBIL Score: The Basics and Beyond" icon={Target} />

        <SubHeader title="1.1. What Exactly is a CIBIL Score?" />
        <motion.p variants={itemVariants}>
          The CIBIL Score is a <strong>3-digit numerical summary</strong> ranging from <strong>300 to 900</strong>, with <strong>NA</strong> (Not Applicable) and <strong>NH</strong> (No History) also appearing for individuals without a credit profile. It is generated by <strong>TransUnion CIBIL</strong>, one of the four key Credit Information Companies (CICs) in India, based on the information in your <strong>Credit Information Report (CIR)</strong>. This report details your entire borrowing and repayment history over the past seven years, reflecting how responsibly you manage debt.
        </motion.p>
        
        <SubHeader title="1.2. The Anatomy of the Credit Information Report (CIR)" />
        <motion.p variants={itemVariants}>
            Your CIBIL Score is merely the tip of the iceberg. The <strong>Credit Information Report (CIR)</strong> holds the critical data points that lenders scrutinize. Understanding these components is essential for deep mastery of your credit profile.
        </motion.p>
         <ul className="list-disc ml-6 space-y-3">
            <BulletPoint text="<strong>Account Information (The Core):</strong> A list of all credit facilities, including <strong>Account Type</strong> (HL, PL, CC), <strong>Lender Name</strong>, <strong>Account Status</strong> (Active, Closed, Settled), and <strong>Current Balance</strong>." />
            <BulletPoint text="<strong>Payment History (The Most Critical):</strong> A month-by-month record of repayment status. Lenders look for <strong>'STD' (Standard)</strong> status continuously for 36 months. Statuses like 'SMA' (Special Mention Account) or 'Doubtful' severely damage your prospects." />
            <BulletPoint text="<strong>Enquiry Information:</strong> A record of all times your credit report was accessed by a lender (<strong>Hard Enquiries</strong>), which indicates frequent loan applications." />
        </ul>

        <SubHeader title="1.3. Why is My CIBIL Score Important for Loans?" />
        <motion.p variants={itemVariants}>
          Lenders view the CIBIL Score as a predictive risk indicator. A high score suggests a low risk of default, making you an attractive borrower.
        </motion.p>
        <ul className="list-none space-y-3">
          <BulletPoint text="<strong>Faster Approval:</strong> High CIBIL scores (750+) often lead to instant or priority loan processing." />
          <BulletPoint text="<strong>Lower Interest Rates:</strong> Banks offer <strong>preferential pricing</strong> and better interest rates (0.5% to 2.0% lower) to customers with excellent credit scores, saving you thousands over the loan tenure." />
          <BulletPoint text="<strong>Higher Loan Amounts:</strong> Demonstrating strong repayment discipline allows lenders to offer higher principal amounts." />
          <BulletPoint text="<strong>Negotiation Power:</strong> A robust score gives you leverage to negotiate loan terms and processing fees." />
        </ul>

        {/* SECTION 2: Calculation and Weightage (Deep Dive) */}
        <SectionHeader title="2. The CIBIL Score Calculation Formula (Weightage Breakdown)" icon={Scale} />

        <SubHeader title="2.1. The 4 Critical Components of CIBIL Score" />
        <motion.p variants={itemVariants}>
          CIBIL uses a complex proprietary algorithm, but the weightage of the contributing factors is generally consistent across all credit bureaus. Here is the approximate breakdown:
        </motion.p>

        <motion.div className="overflow-x-auto" variants={itemVariants}>
          <table className="min-w-full divide-y divide-gray-200 shadow-md rounded-lg">
            <thead className="bg-blue-100">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-600 uppercase tracking-wider">Factor</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-600 uppercase tracking-wider">Approx. Weightage</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-600 uppercase tracking-wider">Advanced Impact Description</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              <motion.tr variants={itemVariants}>
                <td className="px-6 py-4 whitespace-nowrap font-semibold">Payment History</td>
                <td className="px-6 py-4 whitespace-nowrap text-red-600 font-bold">~35%</td>
                <td className="px-6 py-4">Timeliness of EMI and credit bill payments. <strong>Perfection is Mandatory.</strong> Settlements and Write-Offs are severely detrimental.</td>
              </motion.tr>
              <motion.tr variants={itemVariants}>
                <td className="px-6 py-4 whitespace-nowrap font-semibold">Credit Utilization Ratio (CUR)</td>
                <td className="px-6 py-4 whitespace-nowrap text-indigo-600 font-bold">~30%</td>
                <td className="px-6 py-4">Total credit used versus total credit limit. <strong>Optimal CUR is 10%-20%</strong>. Keep it strictly below 30%.</td>
              </motion.tr>
              <motion.tr variants={itemVariants}>
                <td className="px-6 py-4 whitespace-nowrap font-semibold">Credit Mix and Age</td>
                <td className="px-6 py-4 whitespace-nowrap text-green-600 font-bold">~15%</td>
                <td className="px-6 py-4">A mix of secured (Home/Auto) and unsecured (CC/PL) debt over a long period. Longer age signals stability.</td>
              </motion.tr>
              <motion.tr variants={itemVariants}>
                <td className="px-6 py-4 whitespace-nowrap font-semibold">New Credit Enquiries</td>
                <td className="px-6 py-4 whitespace-nowrap text-yellow-600 font-bold">~10%</td>
                <td className="px-6 py-4">The frequency of <strong>Hard Enquiries</strong> (loan applications). Too many in a short time signals desperation. Limit applications.</td>
              </motion.tr>
              <motion.tr variants={itemVariants}>
                <td className="px-6 py-4 whitespace-nowrap font-semibold">Other Factors</td>
                <td className="px-6 py-4 whitespace-nowrap text-gray-500 font-bold">~10%</td>
                <td className="px-6 py-4">Defaults, guarantor status on defaulted loans, and data reporting errors.</td>
              </motion.tr>
            </tbody>
          </table>
        </motion.div>

        <SubHeader title="2.2. Understanding and Optimizing Credit Utilization Ratio (CUR)" />
        <motion.p variants={itemVariants}>
           The CUR is calculated based on the balance your bank reports to CIBIL, which is usually around the statement generation date. The optimal CUR is $10\% - 20\%$. To maximize your score, you must actively manage this ratio.
        </motion.p>
        <motion.blockquote variants={itemVariants} className="p-3 bg-indigo-50 border-l-4 border-indigo-500 italic text-gray-700">
            <strong>Pro-Tip: The Statement Date Trick.</strong> If your credit limit is ₹1,00,000, and you spend ₹70,000, immediately pay ₹50,000 before the statement generation date. The bank will report a low outstanding balance of ₹20,000 (a 20% CUR), boosting your score, even if you pay the remaining ₹20,000 later.
        </motion.blockquote>

        <SubHeader title="2.3. Score Tier Classification and Lender Perception" />
        <motion.p variants={itemVariants}>
          While 750 is the minimum for a good rate, aiming for above 800 places you in the 'Super Prime' category for guaranteed approval and the best deals.
        </motion.p>
        <ul className="list-disc ml-6 space-y-2">
            <li><strong>800 - 900 (Excellent/Prime):</strong> Best-in-market rates, nearly 100% approval.</li>
            <li><strong>750 - 799 (Very Good/Preferred):</strong> Excellent rates, high likelihood of approval for most products.</li>
            <li><strong>700 - 749 (Good/Standard):</strong> Standard rates, may face rejection from strict lenders for large loans.</li>
        </ul>
        
        {/* SECTION 3: Advanced Improvement Strategies */}
        <SectionHeader title="3. Boosting Your CIBIL Score Above 750 (Advanced Tactics)" icon={TrendingUp} />

        <SubHeader title="3.1. Master the 36-Month Repayment Window" />
        <motion.p variants={itemVariants}>
          Lenders focus intensely on the last <strong>36 months (3 years)</strong> of your credit history. One late payment (even 30 Days Past Due, or 30 DPD) within this period is severely damaging. <strong>Implement Auto-Pay</strong> for all EMIs and credit card bills to eliminate this risk entirely.
        </motion.p>

        <SubHeader title="3.2. Strategic Loan Closures and Credit Age" />
        <motion.p variants={itemVariants}>
          To maintain a long credit history (Credit Age), <strong>never close your oldest credit card</strong>, even if you don't use it. Keep it active with a small, periodic transaction. When closing any loan, ensure the bank provides a <strong>'No Dues Certificate'</strong> and follow up to ensure the status is instantly updated to <strong>'Closed'</strong> in the CIBIL report, not 'Settled'.
        </motion.p>
        
        <SubHeader title="3.3. Addressing Negative Marks: Settlement vs. Write-Off" />
        <motion.p variants={itemVariants}>
           A <strong>'Settled'</strong> status means you paid less than the full debt and is a major negative mark, staying on your report for up to 7 years. <strong>'Written-Off'</strong> is the worst status. If possible, pay the remaining difference on a 'Settled' account and request the lender to update the status to <strong>'Closed'</strong> (Paid in Full) to mitigate the long-term damage.
        </motion.p>

        {/* SECTION 4: The Official CIBIL Dispute Resolution Protocol */}
        <SectionHeader title="4. Correcting Your CIR: The CIBIL Dispute Resolution Protocol" icon={FileText} />

        <SubHeader title="4.1. Common CIBIL Report Errors" />
        <motion.p variants={itemVariants}>
           Errors are distressingly common and can depress your score by over 100 points. Regular monitoring and active dispute filing are essential tools for CIBIL mastery.
        </motion.p>
        <ul className="list-disc ml-6 space-y-3">
          <BulletPoint text="<strong>Incorrect Account Status:</strong> Your loan is marked 'Settled' when you paid in full ('Closed'). <strong>Remedy:</strong> Submit the 'No Dues Certificate' (NDC) from the lender." />
          <BulletPoint text="<strong>Incorrect Balance/Limit:</strong> Outstanding amount is higher than actual, artificially inflating your CUR. <strong>Remedy:</strong> Provide the latest statement from the lender." />
          <BulletPoint text="<strong>Accounts Not Yours (Fraud):</strong> Credit facilities you never availed of are listed. <strong>Remedy:</strong> File a police complaint (FIR) and submit a copy along with your dispute." />
        </ul>

        <SubHeader title="4.2. The Official Dispute Filing Process" />
        <motion.p variants={itemVariants}>
            You must file the dispute directly through the TransUnion CIBIL website. CIBIL acts as a facilitator, forwarding the dispute to the concerned bank, which is legally obligated to investigate and respond within <strong>30-45 days</strong>. Your score will be re-calculated upon correction.
        </motion.p>

        {/* SECTION 5: CIBIL and Loan Types */}
        <SectionHeader title="5. CIBIL Requirements for Specific Financial Products" icon={DollarSign} />

        <motion.p variants={itemVariants}>
          The score required for approval varies by product type and the risk profile of the lender (PSU Bank vs. Private Bank vs. NBFC).
        </motion.p>

        <SubHeader title="5.1. Home Loan Eligibility (The Highest Requirement)" />
        <motion.p variants={itemVariants}>
          Due to the high ticket size and long tenure, banks are extremely strict. A score below 720 may lead to immediate rejection. <strong>750 to 800+ is essential</strong> for competitive Home Loan interest rates. Borrowers with slightly lower scores may be asked to contribute a higher margin money (down payment).
        </motion.p>

        <SubHeader title="5.2. Personal Loan and Credit Card Approval" />
        <motion.p variants={itemVariants}>
          These are unsecured debts and thus carry high risk. The minimum acceptable score is typically <strong>680 to 700</strong>, but scores below 730 will result in extremely high interest charges (often 18% to 25% APR), as the bank prices in the higher risk.
        </motion.p>

        <SubHeader title="5.3. Business Loan and MSME Implications" icon={Briefcase} />
        <motion.p variants={itemVariants}>
          For sole proprietorships and partnerships, the applicant's <strong>personal CIBIL score</strong> is the primary factor. A score below 750 can severely limit the borrowing capacity and increase the rate on the Business Loan. Maintaining a stellar score is non-negotiable for entrepreneurs seeking capital.
        </motion.p>


        {/* SECTION 6: Frequently Asked Questions (SEO Optimization) */}
        <SectionHeader title="6. CIBIL Score FAQs (Expert Insights)" icon={HelpCircle} />

        <SubHeader title="Q: How long does it take to improve CIBIL score?" />
        <motion.p variants={itemVariants}>
          A significant improvement (e.g., from 650 to 750) generally takes <strong>6 to 12 months</strong> of consistent, disciplined financial behavior (timely payments and low CUR). This period allows the positive data to establish a favorable trend. Minor fixes, like dispute resolution, can show results in 30-45 days.
        </motion.p>

        <SubHeader title="Q: Does checking my CIBIL score hurt it?" />
        <motion.p variants={itemVariants}>
          No. Checking your own score (a <strong>Soft Enquiry</strong>) does not affect your score. Only loan applications initiated by lenders (a <strong>Hard Enquiry</strong>) impact the score negatively, and only if done frequently. Always use platforms that offer soft credit checks before formally applying.
        </motion.p>

        <SubHeader title="Q: What if I have no credit history (NA or NH)?" />
        <motion.p variants={itemVariants}>
          'NA' or 'NH' means you have never taken a loan or credit card. Lenders cannot assess your risk. To build a profile, start with a small <strong>Secured Credit Card</strong> (backed by a Fixed Deposit) or a small gold loan. These secured facilities are the safest way to establish a positive repayment history.
        </motion.p>

        <SubHeader title="Q: Should I use multiple credit cards?" />
        <motion.p variants={itemVariants}>
          Yes, strategically. Having multiple cards with large limits allows you to distribute your spending, making it easier to maintain the optimal 10% - 20% Credit Utilization Ratio on each card. For example, a single card with a <strong>₹1 lakh limit</strong> and ₹40k spent has a <strong>40% CUR</strong>. Two cards, each with a <strong>₹1 lakh limit</strong> and ₹20k spent on each, have a <strong>20% CUR</strong> overall, which is far better for your score.
        </motion.p>

        {/* CONCLUSION */}
        <motion.section variants={itemVariants} className="mt-12 p-6 bg-yellow-50 border-l-4 border-yellow-500 rounded-lg">
          <h4 className="text-xl font-bold text-gray-900 mb-3">Final Thoughts on Financial Mastery</h4>
          <p>
            The CIBIL score is your lifelong financial resume. By focusing on timely payments, low utilization, and diligent monitoring, you are not just building a score—you are building trust with India's financial ecosystem. This dedication ensures that when the time comes for a major purchase, be it a car or a home, your financing options will be affordable and plentiful. <strong>Mastering your CIBIL score is mastering your financial future.</strong>
          </p>
        </motion.section>

        {/* CTA Section */}
        <motion.section
          className="text-center mt-16 p-8 bg-gradient-to-r from-blue-600 to-indigo-700 rounded-2xl shadow-xl"
          variants={pageVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.2 }}
        >
          <motion.h2
            className="text-3xl sm:text-4xl font-extrabold text-white mb-4 drop-shadow-lg"
            variants={itemVariants}
          >
            Get Personalized Credit Coaching
          </motion.h2>
          <motion.p
            className="text-lg text-blue-100 mb-8 max-w-2xl mx-auto leading-relaxed"
            variants={itemVariants}
          >
            Receive a personalized action plan to improve your score by 100 points in the next 6 months.
          </motion.p>
          <motion.div variants={itemVariants}>
            <button
              onClick={() => alert("Personalized Action Plan Requested!")}
              className="bg-white text-blue-600 px-8 py-4 rounded-full font-bold text-lg shadow-lg hover:bg-gray-100 transition-all duration-300 ease-in-out transform hover:-translate-y-1 focus:outline-none focus:ring-4 focus:ring-white focus:ring-opacity-50"
            >
              Start My Free Plan
            </button>
          </motion.div>
        </motion.section>

      </article>
    </div>
  </motion.div>
);

export default UltimateCIBILGuidePage;
